server:
  port: 8080

spring:
  application:
    name: AdvancedDatabaseSystems_Project
  datasource:
    url: jdbc:mysql://localhost:3306/ads_project
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
